# Generated by Django 3.2.9 on 2021-11-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
