# Generated by Django 3.2.9 on 2021-11-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyapi', '0003_auto_20211125_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('coupon', models.CharField(max_length=255)),
                ('datetime', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
