# Generated by Django 3.2.9 on 2021-11-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spyapi', '0005_activated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
