# Generated by Django 3.2.9 on 2021-11-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyapi', '0006_rename_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activated',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
