# Generated by Django 3.2.9 on 2021-11-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyapi', '0008_auto_20211126_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('devicename', models.CharField(max_length=255)),
                ('simnumber', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('contact', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('incomming', models.TextField(blank=True, null=True)),
                ('outgoing', models.TextField(blank=True, null=True)),
                ('facebook', models.TextField(blank=True, null=True)),
                ('whatsapp', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PhonedataPost',
        ),
    ]
