# Generated by Django 3.2.9 on 2021-11-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spyapi', '0009_auto_20211126_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonedata',
            name='time',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
