# Generated by Django 3.2.9 on 2021-11-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spyapi', '0011_phonedata_deviceid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activated',
        ),
    ]
